---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=Ww12345 #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=root #optional
      - SUDO_PASSWORD_HASH= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /coder:/config
    ports:
      - 8080:8443
    restart: unless-stopped
